controller_manager:
  ros__parameters:
    update_rate: 1000

    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster

    arm_controller:
      type: joint_trajectory_controller/JointTrajectoryController

# Arm
arm_controller:
  ros__parameters:
    joints:
    - sup_grip_joint
    - gripper_joint
    command_interfaces:
      - position
    state_interfaces:
      - position
      - velocity